version: '3'

services:
  # ユーザー1のリトライサービス
  retry-user1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retry-user1
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - TF_VAR_tenancy_ocid=${USER1_TENANCY_OCID}
      - TF_VAR_user_ocid=${USER1_USER_OCID}
      - TF_VAR_fingerprint=${USER1_FINGERPRINT}
      - TF_VAR_private_key_path=/root/.oci/user1/private.pem
      - TF_VAR_region=${USER1_REGION:-ap-tokyo-1}
      - TF_VAR_compartment_id=${OCI_COMPARTMENT_ID}
      - TF_VAR_availability_domain=${OCI_AVAILABILITY_DOMAIN}
      - TF_VAR_subnet_id=${OCI_SUBNET_ID}
      - TF_VAR_image_id=${OCI_IMAGE_ID}
    volumes:
      - ./terraform:/app/terraform
      - ~/.oci/user1:/root/.oci/user1
    command: >
      --background 
      -v 
      -r 0
      -i 30 
      -b 1.5 
      -m 300 
      -t 600 
      -n
      -d ${DISCORD_WEBHOOK:-}
      -a ${SLACK_WEBHOOK:-}
      "cd /app/terraform && terraform init && terraform apply -auto-approve"

  # ユーザー2のリトライサービス
  retry-user2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retry-user2
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - TF_VAR_tenancy_ocid=${USER2_TENANCY_OCID}
      - TF_VAR_user_ocid=${USER2_USER_OCID}
      - TF_VAR_fingerprint=${USER2_FINGERPRINT}
      - TF_VAR_private_key_path=/root/.oci/user2/private.pem
      - TF_VAR_region=${USER2_REGION:-ap-tokyo-1}
      - TF_VAR_compartment_id=${OCI_COMPARTMENT_ID}
      - TF_VAR_availability_domain=${OCI_AVAILABILITY_DOMAIN}
      - TF_VAR_subnet_id=${OCI_SUBNET_ID}
      - TF_VAR_image_id=${OCI_IMAGE_ID}
    volumes:
      - ./terraform:/app/terraform
      - ~/.oci/user2:/root/.oci/user2
    command: >
      --background 
      -v 
      -r 0
      -i 30 
      -b 1.5 
      -m 300 
      -t 600 
      -n
      -d ${DISCORD_WEBHOOK:-}
      -a ${SLACK_WEBHOOK:-}
      "cd /app/terraform && terraform init && terraform apply -auto-approve"

  # ユーザー3のリトライサービス
  retry-user3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retry-user3
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - TF_VAR_tenancy_ocid=${USER3_TENANCY_OCID}
      - TF_VAR_user_ocid=${USER3_USER_OCID}
      - TF_VAR_fingerprint=${USER3_FINGERPRINT}
      - TF_VAR_private_key_path=/root/.oci/user3/private.pem
      - TF_VAR_region=${USER3_REGION:-ap-tokyo-1}
      - TF_VAR_compartment_id=${OCI_COMPARTMENT_ID}
      - TF_VAR_availability_domain=${OCI_AVAILABILITY_DOMAIN}
      - TF_VAR_subnet_id=${OCI_SUBNET_ID}
      - TF_VAR_image_id=${OCI_IMAGE_ID}
    volumes:
      - ./terraform:/app/terraform
      - ~/.oci/user3:/root/.oci/user3
    command: >
      --background 
      -v 
      -r 0
      -i 30 
      -b 1.5 
      -m 300 
      -t 600 
      -n
      -d ${DISCORD_WEBHOOK:-}
      -a ${SLACK_WEBHOOK:-}
      "cd /app/terraform && terraform init && terraform apply -auto-approve"

  # ユーザー4のリトライサービス
  retry-user4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retry-user4
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - TF_VAR_tenancy_ocid=${USER4_TENANCY_OCID}
      - TF_VAR_user_ocid=${USER4_USER_OCID}
      - TF_VAR_fingerprint=${USER4_FINGERPRINT}
      - TF_VAR_private_key_path=/root/.oci/user4/private.pem
      - TF_VAR_region=${USER4_REGION:-ap-tokyo-1}
      - TF_VAR_compartment_id=${OCI_COMPARTMENT_ID}
      - TF_VAR_availability_domain=${OCI_AVAILABILITY_DOMAIN}
      - TF_VAR_subnet_id=${OCI_SUBNET_ID}
      - TF_VAR_image_id=${OCI_IMAGE_ID}
    volumes:
      - ./terraform:/app/terraform
      - ~/.oci/user4:/root/.oci/user4
    command: >
      --background 
      -v 
      -r 0
      -i 30 
      -b 1.5 
      -m 300 
      -t 600 
      -n
      -d ${DISCORD_WEBHOOK:-}
      -a ${SLACK_WEBHOOK:-}
      "cd /app/terraform && terraform init && terraform apply -auto-approve"

  # ユーザー5のリトライサービス
  retry-user5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retry-user5
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - TF_VAR_tenancy_ocid=${USER5_TENANCY_OCID}
      - TF_VAR_user_ocid=${USER5_USER_OCID}
      - TF_VAR_fingerprint=${USER5_FINGERPRINT}
      - TF_VAR_private_key_path=/root/.oci/user5/private.pem
      - TF_VAR_region=${USER5_REGION:-ap-tokyo-1}
      - TF_VAR_compartment_id=${OCI_COMPARTMENT_ID}
      - TF_VAR_availability_domain=${OCI_AVAILABILITY_DOMAIN}
      - TF_VAR_subnet_id=${OCI_SUBNET_ID}
      - TF_VAR_image_id=${OCI_IMAGE_ID}
    volumes:
      - ./terraform:/app/terraform
      - ~/.oci/user5:/root/.oci/user5
    command: >
      --background 
      -v 
      -r 0
      -i 30 
      -b 1.5 
      -m 300 
      -t 600 
      -n
      -d ${DISCORD_WEBHOOK:-}
      -a ${SLACK_WEBHOOK:-}
      "cd /app/terraform && terraform init && terraform apply -auto-approve"