version: '3'

services:
  retry:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: oci-instance-retry
    environment:
      - TZ=Asia/Tokyo
      - TF_VAR_tenancy_ocid=${TF_VAR_tenancy_ocid}
      - TF_VAR_user_ocid=${TF_VAR_user_ocid}
      - TF_VAR_fingerprint=${TF_VAR_fingerprint}
      - TF_VAR_private_key_path=/root/.oci/private.pem
      - TF_VAR_region=${TF_VAR_region:-ap-tokyo-1}
      - TF_VAR_compartment_id=${TF_VAR_compartment_id}
      - TF_VAR_availability_domain=${TF_VAR_availability_domain}
      - TF_VAR_subnet_id=${TF_VAR_subnet_id}
      - TF_VAR_image_id=${TF_VAR_image_id}
    volumes:
      - ./terraform:/app/terraform
      - ~/.oci:/root/.oci
    command: >
      --background 
      -v 
      -r 100 
      -i 30 
      -b 1.5 
      -m 300 
      -t 600 
      -n
      -d ${DISCORD_WEBHOOK:-}
      -a ${SLACK_WEBHOOK:-}
      "cd /app/terraform && terraform init && terraform apply -auto-approve"